//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.29 at 06:55:11 PM EST 
//


package com.brix.tc.zip.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.brix.tc.zip.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.brix.tc.zip.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZipConstraints }
     * 
     */
    public ZipConstraints createZipConstraints() {
        return new ZipConstraints();
    }

    /**
     * Create an instance of {@link ZipConstraints.ZIPConstraint }
     * 
     */
    public ZipConstraints.ZIPConstraint createZipConstraintsZIPConstraint() {
        return new ZipConstraints.ZIPConstraint();
    }

}
